export const excistingData = [
    {
        id: 1,
        name: "0001",
        course: "Course 1",
        startingDate: "1 - Sentabr",
        when: "Juft kunlar - 2:00",
        teacher: "Otabek",
        assistant: "Aziza",
        N_of_App: "20",
    },
    {
        id: 2,
        name: "0002",
        course: "Course 5",
        startingDate: "15 - Sentabr",
        endingDate: "10 - Mart",
        when: "Toq kunlar - 4:00",
        teacher: "Otabek",
        assistant: "Aziza",
        N_of_App: "17",
    },
    {
        id: 3,
        name: "0003",
        course: "Course 3",
        startingDate: "15 - Sentabr",
        when: "Toq kunlar - 4:00",
        teacher: "Otabek",
        assistant: "Aziza",
        N_of_App: "16",
    },
    {
        id: 4,
        name: "0004",
        course: "Course 8",
        startingDate: "10 - Dekabr",
        when: "Toq kunlar - 2:00",
        teacher: "Otabek",
        assistant: "Aziza",
        N_of_App: "24",
    },
];