export const pendingData = [
    {
        id: 1,
        name: "0001",
        course: "Course 1",
        startingDate: "1 - Sentabr",
        endingDate: "10 - Mart",
        when: "Juft kunlar - 2:00",
        teacher: "Otabek",
        assistant: "Aziza",
        status: "",
    },
    {
        id: 2,
        name: "0002",
        course: "Course 5",
        startingDate: "15 - Sentabr",
        endingDate: "20 - Mart",
        when: "Toq kunlar - 4:00",
        teacher: "Otabek",
        assistant: "Aziza",
        status: "",
    },
    {
        id: 3,
        name: "0003",
        course: "Course 3",
        startingDate: "15 - Sentabr",
        endingDate: '3 - Aprel',
        when: "Toq kunlar - 4:00",
        teacher: "Otabek",
        assistant: "Aziza",
        status: "",
    },
    {
        id: 4,
        name: "0004",
        course: "Course 8",
        startingDate: "10 - Dekabr",
        endingDate: "20 - Aprel",
        when: "Toq kunlar - 2:00",
        teacher: "Otabek",
        assistant: "Aziza",
        status: "",
    },
];
